print("Generating markstats.pdf from marks.csv")
marksdata <- read.csv("marks.csv")
marks <- na.omit(marksdata$Midsem.exam)
pdf(file='markstats.pdf')
hist(marks,breaks=0:21-0.5,prob=TRUE,xlab="Marks",main=sprintf("Midsem exam, mean %.2f, median %.0f, stdev %.2f", mean(marks), median(marks), sd(marks)))
lines(density(marks,bw="SJ"))
dev.off()
